LOAD DATA INFILE 'C:\\ConvertedCounties2023Dated.csv'
INTO TABLE sightings_2023
FIELDS TERMINATED BY ',' 
ENCLOSED BY '' 
LINES TERMINATED BY '\n'
IGNORE 2 ROWS
(LOCAL_DATE, REPORTINGS, CITY_NAME, STATE_ABREV, COUNTY_NAME, @dummy2, @dummy3, @dummy4, @dummy5);