LOAD DATA INFILE 'C:\\ConvertedCounties2014Dated.csv'
INTO TABLE sightings_2014
FIELDS TERMINATED BY ',' 
ENCLOSED BY '' 
LINES TERMINATED BY '\n'
IGNORE 2 ROWS
(LOCAL_DATE, REPORTINGS, CITY_NAME, STATE_ABREV, COUNTY_NAME, @dummy2, @dummy3);