USE datathon;
CREATE TABLE aqi_2014 (
    STATE_NAME CHAR(40),
    COUNTY_NAME CHAR(23),
    STATE_CODE INT,
    COUNTY_CODE INT,
    LOCAL_DATE DATE,
    AQI INT,
    CATEGORY CHAR(60),
    DEFINING_PARAMETER CHAR(10),
    DEFINING_SITE CHAR(15),
    SITES_REPORTING INT    
);